### ISSUE TITLE
License file contains Apache license, source code files contain GPL license

### ISSUE THREAD

**Issue by 0xC0FFEEC0DE** [SecUSo/privacy-friendly-todo-list#116]
The license file in the root of the repository contains the Apache license, the source code files contain header for the GPL license.
That is not correct. ALL texts should be either Apache license or GPL license, but not mixed.

**Comment by udenr** [comment]
Since most of our apps use GPL v3 and to our knowledge it would not be a problem to change the license from Apache to GPL, we would suggest to change the license for this repository to [GPL v3](https://github.com/SecUSo/privacy-friendly-notes/blob/b3efd3f7f86011adbb554aa225c9aa3d4a2eb401/LICENSE).

I would be happy if all contributors (@Naitbobbes @sbreitf1 @Kamuno @Yonjuni @sleep-yearning @0xC0FFEEC0DE @nico1509 @coderPaddyS @jahway603 @petermayer @steelman @redfast00 @naofum ) could briefly comment here on this issue whether they agree with the change to GPL v3.

As soon as everyone agrees, I would then create a pull request with the license change and invite everyone as a reviewer.

**Comment by redfast00** [comment]
I permit the license of my contributions to the SecUSo/privacy-friendly-todo-list project to be changed to the GPLv3 license.

Additionally, I assign copyright ownership of my project contributions to the SecUSo/privacy-friendly-todo-list project.

**Comment by Kamuno** [comment]
I agree :)

**Comment by 0xC0FFEEC0DE** [comment]
I agree to change my contributions to SecUSo/privacy-friendly-todo-list to GPL v3.

**Comment by steelman** [comment]
I agree on the license change.

**Comment by coderPaddyS** [comment]
I agree :D

**Comment by petermayer** [comment]
I agree 👍

**Comment by udenr** [comment]
Could you please also comment on whether you agree? @sbreitf1 @Yonjuni @sleep-yearning @nico1509 @jahway603 @naofum 

Thanks to everyone who has already commented.

**Comment by nico1509** [comment]
I agree

**Comment by sleep-yearning** [comment]
I agree to the proposed licence change to GPL.

**Comment by sbreitf1** [comment]
I agree

**Comment by udenr** [comment]
I've just created a pull request (#129) with the license change, and I would appreciate it if you could add an approving review to indicate your approval.

**Comment by 0xC0FFEEC0DE** [comment]
PR #129 was merged to master and so fixes this issue.
