### ISSUE TITLE
Bug Found in To do List apps (App crashes  when i try to open the to do list apps ) 

### ISSUE THREAD

**Issue by abdulmalikkhan655** [SecUSo/privacy-friendly-todo-list#47]
#### Expected behavior
when i click on the to do list  application icon it should be open and show all the features

#### Actual behavior
when i click on the To do list application  icon for open the application App is crashes and showing error of unfortunately to do list has stopped  
#### How to reproduce
* [Download ](https://f-droid.org/packages/org.secuso.privacyfriendlytodolist/)and open the application 
* note Bug 
* Browser: To-Do List version 2.1

* Operating system: android version 4.4.2

* smart phone GALAXY Note 3
#### Recording Of The Bug
https://youtu.be/TpYHvkJ2KDk

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@abdulmalikkhan/bug-found-in-to-do-list-apps-app-crashes-when-i-try-to-open-the-to-do-list-apps">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by tobias-g1** [comment]
Hello, I'm one of the moderators at Utopian and I thought it would be useful if I provided some additional information surrounding this issue which I believe you may find useful.

When trying to replicate this particular issue we were unable to replicate it on the following Android versions 7.0, 5.1, 5.0.2 and 6.0.1, however, we were able to replicate this particular issue on 4.4.4. We have had similar reports submitted to Utopian which suggests that this issue is present on 4.4.4, 7.0 & 5.1 however we could not replicate on the versions mentioned previously. As I realize that this particular issue may be hard to replicate for yourself as shown in our efforts in testing I would be more than happy to provide logs at your request, test the issue post a potential fix and provide any further information where I can to help assist you in solving this issue.

Thanks,
Tobias
_Utopian Moderator__

**Comment by StephanieLabaule** [comment]
Hello,
Exactly the same thing here since the update today.
Android v7.0

**Comment by StephanieLabaule** [comment]
Hello,
Exactly the same thing here since the update today.
Android v7.0.

Precision:
Unable to reinstall v2.0 from above (error message: package seems corrupted).
Only option: uninstall v2.1. But in this case, all the tasks are deleted. Not good news.

**Comment by petermayer** [comment]
Hi!

Thank you for reporting this issue. We are looking into it.

@StephanieLabaule which Smartphone do you use? Is it vendor stock v7.0 or did you install an aftermarket Andoird firmware?

**Comment by StephanieLabaule** [comment]
Hello,
Thank you for your reply. It is a recent Motorola G5 with Android vendor stock v7.0.

**Comment by Yonjuni** [comment]
Would it be possible for someone to reproduce the issue while the device is connected to ADB on a PC? Then it would be possible to get the stacktrace and more insight into the issue.

**Comment by StephanieLabaule** [comment]
Hello,

Following the problem of version 2.1 crash resolved in principle for a year, when can we expect an update and use again Todo-list?

Thank you.
