### ISSUE TITLE
UI overlaps Todo text

### ISSUE THREAD

**Issue by PeterHindes** [SecUSo/privacy-friendly-todo-list#68]
Observe the bottom right of the attached image.
![Screenshot_20200305-231441__01__01](https://user-images.githubusercontent.com/19994487/76057867-02eb3e00-5f38-11ea-87f9-a8654cb47949.jpg)

**Comment by 0xC0FFEEC0DE** [comment]
Hello @PeterHindes , Hello @udenr , would it be an acceptable solution to make the + button semi-transparent?

Otherwise the height of the task list could be reduced so that there is space for a bar at the bottom. The + button would be on that bar and would no longer hide the text. Disadvantage: We would loose space for the task list.

**Comment by udenr** [comment]
I guess the current problem is only with the last item in the list? Because for every other item, you could just scroll down to see it.

One option I like is to add some padding to the bottom of the list so that you can always scroll down a little further than the last item. You can try adding the following attributes to the ListView to see if that solves the problem:
```
android:paddingBottom="80dp"
android:clipToPadding="false"
```

**Comment by 0xC0FFEEC0DE** [comment]
Thanks @udenr , your suggestion works well.
